### PR TITLE
fix: properly handle missing algorithm type

### PR DESCRIPTION
**Pull request by ahmedwelhakim**
Fixing a bug that happen in npm cli when installing a library.

in Line 272 the result of parse can be null if integrity is null. Then in line 273 other is null so it breaks as below:
```
TypeError: Cannot read properties of null (reading 'pickAlgorithm')
npm verb stack     at Integrity.match (/usr/lib/node_modules/npm/node_modules/ssri/lib/index.js:273:24)
npm verb stack     at CachePolicy.satisfies (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/policy.js:112:49)
npm verb stack     at Function.find (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/entry.js:178:25)
npm verb stack     at async cacheFetch (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js:8:17)
npm verb stack     at async fetch (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js:98:7)
```

```javascript
function parse (sri, opts) {
  if (!sri) {
    return null
  }
  opts = ssriOpts(opts)
  if (typeof sri === 'string') {
    return _parse(sri, opts)
  } else if (sri.algorithm && sri.digest) {
    const fullSri = new Integrity()
    fullSri[sri.algorithm] = [sri]
    return _parse(stringify(fullSri, opts), opts)
  } else {
    return _parse(stringify(sri, opts), opts)
  }
}
```
Here parse can return null if sri is not defined or null.
```javascript
  match (integrity, opts) {
    opts = ssriOpts(opts)
    const other = parse(integrity, opts)
    const algo = other.pickAlgorithm(opts) // HERE WHERE IT BREAKS
    return (
      this[algo] &&
      other[algo] &&
      this[algo].find(hash =>
        other[algo].find(otherhash =>
          hash.digest === otherhash.digest
        )
      )
    ) || false
  }
```
Here `const algo = other.pickAlgoritm(opts)` this where it breaks when `other = null`.
So we need to check whether other = null or not .
so a solution could be 
```javascript
const algo = other?.pickAlgorithm(opts) 
```
OR
```javascript
if(!other) return false;
const algo = other.pickAlgorithm(opts) 
```

## Reference
[https://github.com/npm/cli/issues/5496](url)
[https://github.com/npm/cli/issues/3374](url)

### CODE REVIEW

**Comment by wraithgar** [comment]
The `?` operator is not present in all of the versions of node that this module has to support.

**Comment by ahmedwelhakim** [comment]
> The `?` operator is not present in all of the versions of node that this module has to support.

I removed it.

**Comment by wraithgar** [comment]
This will need a test to cover the `if` statement.

**Comment by ahmedwelhakim** [comment]
> This will need a test to cover the `if` statement.

I added it

**Pull request merged**
